name: DEPLOY TO DEV EC2

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - run: |
        cd app
        npm install

    - name: Create app directory on DEV EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p /home/ubuntu/app-dev

    - name: Deploy to DEV EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app"
        target: "/home/ubuntu/app-dev"
        strip_components: 1

    - name: Start Application on DEV EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/app-dev && pwd && ls -la
          npm install
          pm2 restart app-dev || NODE_ENV=development pm2 start index.js --name "app-dev" --update-env
